name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the default Python 3 version
    - name: Install dependencies
      run: |
        # If you have any dependencies, install them here
        # For example, if you have a requirements.txt file, uncomment the next line
        pip install -r requirements.txt
    - name: Run test script
      run: python test.py
    - name: Check for failures
      run: |
        if grep -q 'FAIL:' test_results.txt; then
          exit 1
        fi
