name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Use the default Python 3 version
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run test script
      run: python test.py
    - name: Check for failures
      run: |
        if grep -q 'FAIL:' test_results.txt; then
          exit 1
        fi
